### ISSUE TITLE
GitHub API missing page parameter 

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/unofficial_openapi_specs#12]
Moving to relevant repo.

@bobby-brennan wrote:

> Every "list" operation should have a page parameter

How close is the scrape-to-swagger version of GitHub v3 to being usable as a replacement?

**Comment by rbren** [comment]
I've gotten it to pass validation, but it's still pretty sketchy. There are a lot of issues with schemas in particular.

That said, it's probably a better long-run solution than the handwritten schema. I'm working on it a bit now, and will spot-check it against the spec here to see how close it is to being correct.

**Comment by MikeRalphson** [comment]
See also https://github.com/octokit/routes/pull/168

**Comment by gr2m** [comment]
👋 Hello friends, I’m working quite actively on moving octokit/routes to use the OpenAPI spec right now, happy to join forces!

octokit/routes is currently complete, and there are a lot of edge cases it handles. The transition to OpenAPI has some challenges and we could definitely use some help from folks that know the OpenAPI spec better than us

For example, a question I have right now is how we could add the preview request headers to the specification?

**Comment by rbren** [comment]
Hi Gregor,

Exciting to hear there will be OpenAPI support!

I think a `header` param should do the trick. It's possible that the fact that it's an `Accept` header could screw some clients up if you're not using the same content type in the responses section.

I think something like:
```
paths:
  /my/operation:
    post:
      parameters:
        - in: header
          name: Accept
          schema:
            type: string
            enum:
              - wyandotte-preview
```
