### ISSUE TITLE
Defaults in Trello getBatch are 'undefined'

### ISSUE THREAD

**Issue by rbren** [APIs-guru/unofficial_openapi_specs#9]
e.g.

```yaml
  /batch:
    get:
      operationId: getBatch
      parameters:
        - default: undefined
          description: 'list of API v1 GET routes, not including the version prefix'
          in: query
          name: urls
          required: true
          type: string
```
